export const discImageArr = [
    // require 强制引入图片
    require('@/assets/img/float_player/float_player_play_01.png'),
    require('@/assets/img/float_player/float_player_play_02.png'),
    require('@/assets/img/float_player/float_player_play_03.png'),
    require('@/assets/img/float_player/float_player_play_04.png'),
    require('@/assets/img/float_player/float_player_play_05.png'),
    require('@/assets/img/float_player/float_player_play_06.png'),
    require('@/assets/img/float_player/float_player_play_07.png'),
    require('@/assets/img/float_player/float_player_play_08.png'),
    require('@/assets/img/float_player/float_player_play_09.png'),
    require('@/assets/img/float_player/float_player_play_10.png'),
    require('@/assets/img/float_player/float_player_play_11.png'),
    require('@/assets/img/float_player/float_player_play_12.png'),
    require('@/assets/img/float_player/float_player_play_13.png'),
    require('@/assets/img/float_player/float_player_play_14.png'),
    require('@/assets/img/float_player/float_player_play_15.png'),
    require('@/assets/img/float_player/float_player_play_16.png'),
    require('@/assets/img/float_player/float_player_play_17.png'),
    require('@/assets/img/float_player/float_player_play_18.png'),
    require('@/assets/img/float_player/float_player_play_19.png'),
    require('@/assets/img/float_player/float_player_play_20.png'),
]